import { TabView } from "./types";

export const APP_NAME = "Nesha";

export const TRANSLATIONS = {
  am: {
    greeting: "ሰላም",
    today: "ዛሬ",
    habits: "ልማዶች",
    chat: "ምክር (AI)",
    notes: "ማስታወሻ",
    profile: "መገለጫ",
    streak: "ተከታታይ",
    addHabit: "አዲስ ልማድ",
    writeNote: "ማስታወሻ ጻፍ...",
    typeMessage: "መንፈሳዊ ምክር፣ የህይወት ጥያቄ ወይም ሀሳብ ይጠይቁ...",
    loading: "በማሰራት ላይ...",
    dailyWisdom: "የዕለቱ ምክር (ነሻ)",
    completed: "ተጠናቀቀ",
    pending: "ይቀራል",
    delete: "ሰርዝ",
    save: "ቀምጥ",
    cancel: "ይቅር",
    language: "ቋንቋ",
    theme: "ገጽታ",
    settings: "ቅንብሮች",
    habitTitle: "የልማዱ ስም",
    habitDesc: "መግለጫ (አማራጭ)",
    frequency: "ድግግሞሽ",
    daily: "በየቀኑ",
    weekly: "በየሳምንቱ",
    aiIntro: "ሰላም! እኔ ነሻ ነኝ። መንፈሳዊ፣ ማህበራዊ ወይም የግል ምክር ከፈለጉ ይጠይቁኝ።",
    welcome: "እንኳን ደህና መጡ",
    setupProfile: "መገለጫዎን ያዋቅሩ",
    editHabit: "ልማድን አርትዕ",
    history: "ታሪክ",
    stats: "ስታትስቲክስ",
    total: "ጠቅላላ",
    last30Days: "የመጨረሻዎቹ 30 ቀናት",
    clearChat: "ቻት አጽዳ",
    copy: "ቅዳ",
    copied: "ተቀድቷል",
    suggestions: "የጥያቄ ሀሳቦች",
    suggestion1: "መንፈሳዊ ጥንካሬ እንዴት ማግኘት እችላለሁ?",
    suggestion2: "ስለ ትዕግስት ምክር ስጠኝ",
    suggestion3: "ጥሩ ልማድ ለማዳበር ምን ላድርግ?",
    streakInfoTitle: "ስለ ተከታታይነት (Streak)",
    streakInfoDesc: "ይህ ልማዱን ሳያቋርጡ የሠሩባቸውን ቀናት ይቆጥራል። አንድ ቀን ካለፈዎት ወደ ዜሮ ይመለሳል።",
    streakInfoTip: "ምክር: በየቀኑ በትንሹም ቢሆን መሥራት ለስኬት ወሳኝ ነው።",
    // Analyzer Translations
    myNotes: "የግል ማስታወሻ",
    analyzer: "መንፈሳዊ ህክምና",
    analyzerDesc: "ለማቆም የሚፈልጉት ልማድ ወይም ኃጢአት አለ? እዚህ ይጻፉትና የመፍትሄ ሀሳብ ያግኙ።",
    analyzePlaceholder: "ለምሳሌ፦ በጣም እናደዳለሁ፣ ጸሎት አልወድም፣ ወይም መጥፎ ልማድ አለብኝ...",
    analyzeBtn: "መፍትሄ ፈልግ",
    analyzing: "በመመርመር ላይ...",
    addToHabit: "ወደ ልማድ ጨምር",
    added: "ተጨምሯል",
    recommendations: "የመፍትሄ ሀሳቦች",
    weekDays: ["እ", "ሰ", "ማ", "ረ", "ሐ", "ዓ", "ቅ"],
    // Notification & Confession
    notifications: "ማሳሰቢያዎች",
    confession: "ንስሐ",
    confessionTitle: "የንስሐ ቀጠሮ",
    setConfessionDate: "ቀጠሮ ይያዙ",
    confessionDate: "የንስሐ ቀን",
    daysLeft: "ቀናት ቀሩት",
    confessionVerse: "አቤቱ፥ እንደ ቸርነትህ መጠን ማረኝ፤ እንደ ምሕረትህም ብዛት መተላለፌን ደምስስ። (መዝ 51፥1)",
    confessionPrompt: "የነፍስ አባትዎ ጋር ለመሄድ ያቀዱበትን ቀን ይምረጡ።",
    prepareSoul: "ነፍስዎን ያዘጋጁ",
    upcoming: "የሚመጣው",
    noNotifications: "ምንም አዲስ ማሳሰቢያ የለም",
    lastConfession: "የመጨረሻው ንስሐ",
    markAsDone: "እንደተደረገ ምልክት አድርግ",
    spiritualHealth: "መንፈሳዊ ጤንነት",
    timeToRepent: "ከንስሐ አባትዎ ጋር ከተገናኙ ቆይተዋል።",
    monthAlert: "ከአንድ ወር በላይ ሆኖታል። ነፍስዎን ያድሱ።",
    daysSince: "ቀናት አለፉ",
    untracked: "አልተመዘገበም",
    congratulations: "እንኳን ደስ አለዎት! ነፍስዎን አድሰዋል።",
    // Tasks
    tasks: "ተግባራት",
    addTask: "ተግባር ጨምር",
    taskTitle: "የተግባር ርዕስ",
    dueDate: "የሚጠናቀቅበት ቀን",
    priority: "ደረጃ",
    low: "ዝቅተኛ",
    medium: "መካከለኛ",
    high: "ከፍተኛ",
    reminder: "ማሳሰቢያ",
    setReminder: "ማሳሰቢያ አክል",
    taskReminders: "የተግባር ማሳሰቢያዎች",
    dueTasks: "የሚሰሩ ተግባራት",
    noTasks: "ምንም ተግባር የለም",
    sort: "ደርድር",
    newest: "አዲስ"
  },
  en: {
    greeting: "Selam",
    today: "Today",
    habits: "Habits",
    chat: "Advice (AI)",
    notes: "Notes",
    profile: "Profile",
    streak: "Streak",
    addHabit: "New Habit",
    writeNote: "Write a note...",
    typeMessage: "Ask for spiritual guidance, life advice, or just chat...",
    loading: "Thinking...",
    dailyWisdom: "Daily Wisdom (Nesha)",
    completed: "Completed",
    pending: "Pending",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    language: "Language",
    theme: "Theme",
    settings: "Settings",
    habitTitle: "Habit Title",
    habitDesc: "Description (optional)",
    frequency: "Frequency",
    daily: "Daily",
    weekly: "Weekly",
    aiIntro: "Hello! I am Nesha. Ask me for spiritual, social, or personal advice.",
    welcome: "Welcome",
    setupProfile: "Setup Profile",
    editHabit: "Edit Habit",
    history: "History",
    stats: "Statistics",
    total: "Total",
    last30Days: "Last 30 Days",
    clearChat: "Clear Chat",
    copy: "Copy",
    copied: "Copied",
    suggestions: "Suggestions",
    suggestion1: "How do I gain spiritual strength?",
    suggestion2: "Give me advice on patience",
    suggestion3: "How to build good habits?",
    streakInfoTitle: "About Streaks",
    streakInfoDesc: "A streak counts consecutive days you complete this habit. Missing a day resets it to zero.",
    streakInfoTip: "Tip: Consistency is key. Even a small effort counts!",
    // Analyzer Translations
    myNotes: "My Notes",
    analyzer: "Spiritual Analyzer",
    analyzerDesc: "Is there a habit or sin you want to quit? Write it here to get spiritual remedies.",
    analyzePlaceholder: "E.g., I get angry easily, I struggle with prayer, or I have a bad habit...",
    analyzeBtn: "Analyze",
    analyzing: "Analyzing...",
    addToHabit: "Add to Habits",
    added: "Added",
    recommendations: "Recommendations",
    weekDays: ["S", "M", "T", "W", "T", "F", "S"],
    // Notification & Confession
    notifications: "Notifications",
    confession: "Confession",
    confessionTitle: "Confession Schedule",
    setConfessionDate: "Schedule Date",
    confessionDate: "Confession Date",
    daysLeft: "days left",
    confessionVerse: "Have mercy upon me, O God, according to Your lovingkindness; according to the multitude of Your tender mercies, blot out my transgressions. (Ps 51:1)",
    confessionPrompt: "Choose the date you plan to visit your spiritual father.",
    prepareSoul: "Prepare Your Soul",
    upcoming: "Upcoming",
    noNotifications: "No new notifications",
    lastConfession: "Last Confession",
    markAsDone: "Mark as Done",
    spiritualHealth: "Spiritual Health",
    timeToRepent: "It has been a while since your last confession.",
    monthAlert: "It has been over a month. Renew your soul.",
    daysSince: "days since",
    untracked: "Not tracked",
    congratulations: "Congratulations! Your soul is renewed.",
    // Tasks
    tasks: "Tasks",
    addTask: "Add Task",
    taskTitle: "Task Title",
    dueDate: "Due Date",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    reminder: "Reminder",
    setReminder: "Set Reminder",
    taskReminders: "Task Reminders",
    dueTasks: "Due Tasks",
    noTasks: "No tasks pending",
    sort: "Sort",
    newest: "Newest"
  }
};

export const ETHIOPIAN_MONTHS = [
  "Meskerem", "Tikimt", "Hidar", "Tahsas", "Tir", "Yekatit",
  "Megabit", "Miazia", "Genbot", "Sene", "Hamle", "Nehase", "Pagume"
];

export const ETHIOPIAN_MONTHS_AM = [
  "መስከረም", "ጥቅምት", "ህዳር", "ታህሳስ", "ጥር", "የካቲት",
  "መጋቢት", "ሚያዚያ", "ግንቦት", "ሰኔ", "ሐምሌ", "ነሐሴ", "ጳጉሜ"
];

export const NAV_ITEMS: { id: TabView; icon: string; labelKey: keyof typeof TRANSLATIONS.en }[] = [
  { id: 'home', icon: 'Home', labelKey: 'today' },
  { id: 'habits', icon: 'ListChecks', labelKey: 'habits' },
  { id: 'chat', icon: 'Sparkles', labelKey: 'chat' },
  { id: 'notes', icon: 'NotebookPen', labelKey: 'notes' },
  { id: 'profile', icon: 'User', labelKey: 'profile' },
];